version: 2.1
jobs:
  build1:
    docker:
      - image: 'circleci/node:8.11.1'
    steps:
      - checkout
      - run:
          name: Testing website build
          command: |
            git config --global user.email "pjayathissa@users.noreply.github.com"
            git config --global user.name "pjayathissa"
            echo "machine github.com login pjayathissa password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=pjayathissa yarn run build

  build2:
    docker:
      - image: 'circleci/node:8.11.1'
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "pjayathissa@users.noreply.github.com"
            git config --global user.name "pjayathissa"
            echo "machine github.com login pjayathissa password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=pjayathissa yarn run publish-gh-pages

workflows:
  build_and_test: # name of your workflow
    jobs:
      - build1:
      - build2: