version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.11.1'
    branches:
      ignore: gh-pages
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "pjayathissa@users.noreply.github.com"
            git config --global user.name "pjayathissa"
            echo "machine github.com login pjayathissa password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=pjayathissa yarn run publish-gh-pages